Moved release tag to release branch

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -14,6 +14,7 @@ jobs:
     steps:
       - uses: actions/checkout@v3
         with:
+          ref: master
           fetch-depth: 0
 
       - uses: actions/setup-node@v3
@@ -32,35 +33,71 @@ jobs:
         run: |
           gh auth setup-git
 
-      - id: create-release
+      - id: git-push
         env:
           GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
-          BASE_TAG=$(gh api \
+          BASE_RELEASE=$(gh api \
             -H "Accept: application/vnd.github+json" \
             "/repos/$GITHUB_REPOSITORY/releases/latest" \
             -q .tag_name)
+          echo "::notice:: Base release is $BASE_RELEASE"
+          echo "::set-output name=base-release::$BASE_RELEASE"
+
+          BASE_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
           echo "::notice:: Base tag is $BASE_TAG"
           echo "::set-output name=base-tag::$BASE_TAG"
+
+          if [ "$BASE_RELEASE" != "$BASE_TAG" ]
+          then
+            echo "::error:: Most recent release and most recent tag don't match: $BASE_RELEASE vs $BASE_TAG"
+            exit 1
+          fi
 
           if test $(git diff --name-only $BASE_TAG | wc -l) != 0
           then
             git diff --name-only $BASE_TAG | xargs -n1 -I {} echo "::notice file={}::  File: {}"
 
             npm version patch
-            HEAD_TAG=$(git describe --abbrev=0 --tags)
+            HEAD_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
             echo "::notice:: Head tag is $HEAD_TAG"
             echo "::set-output name=head-tag::$HEAD_TAG"
-            git push --follow-tags --force-with-lease
 
-            gh api \
-              --method POST \
-              -H "Accept: application/vnd.github+json" \
-              "/repos/$GITHUB_REPOSITORY/releases" \
-              -f tag_name="$HEAD_TAG" \
-              -f name="$HEAD_TAG" \
-              -F generate_release_notes=true
+            BRANCH_NAME="workflows/releases/$HEAD_TAG"
+            echo "::notice:: Branch name is $BRANCH_NAME"
+            echo "::set-output name=branch-name::$BRANCH_NAME"
+
+            git checkout -b "$BRANCH_NAME"
+            git push -f --set-upstream origin "$BRANCH_NAME" --follow-tags
           fi
+
+      - id: create-pr
+        if: ${{ steps.git-push.outputs.head-tag != '' }}
+        env:
+          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          HEAD_TAG: ${{ steps.git-push.outputs.head-tag }}
+        run: |
+          gh pr create \
+            --base "master" \
+            --title "Release $HEAD_TAG" \
+            --body "#pass2ship"
+          PR_NUMBER=`gh pr view | grep 'number:' | cut -f 2`
+          echo "::set-output name=pr-number::$PR_NUMBER"
+          echo "::notice::PR number is $PR_NUMBER"
+
+      - id: create-release
+        if: ${{ steps.git-push.outputs.head-tag != '' }}
+        env:
+          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          HEAD_TAG: ${{ steps.git-push.outputs.head-tag }}
+        run: |
+          gh api \
+            --method POST \
+            -H "Accept: application/vnd.github+json" \
+            "/repos/$GITHUB_REPOSITORY/releases" \
+            -f tag_name="$HEAD_TAG" \
+            -f name="$HEAD_TAG" \
+            -F generate_release_notes=true
 
   publish:
     needs: release
